### ISSUE TITLE
Roll result not displaying in chat (maybe same color as background)

### ISSUE THREAD

**Issue by waryjack** [waryjack/ewhen08x#17]

**Comment by Jerrikus2k** [comment]
Same behavior. After login first roll works. After that all subsequent rolls are not goind displayed. Thanks for looking into this.

Foundry v9.269
Everywhen v0.9.5
No Active Modules

![error_everywhen](https://user-images.githubusercontent.com/62856579/164894061-bd22fa1b-3b98-421c-8bb3-eded8d36a44a.JPG)

**Comment by KarstenW76** [comment]
Confirmed, sometimes same issue here. Would be great if you get the chance to fix this. Thank you in advance!

This is also by rolling Armor. If you choose a variable amount and take one with a penalty (f.e. 1d6-2), the result is just a black box (if you choose 1d6 the result is shown).
