### ISSUE TITLE
Error message when rolling Task Roll with "Career"

### ISSUE THREAD

**Issue by MadBlue2112** [waryjack/ewhen08x#18]
When selecting a Career for a Task Roll, I get the following error:

TypeError: Cannot read properties of undefined (reading 'data')

Task Rolls work correctly when selecting Main Attribute and Combat Attribute (although, as was mentioned as a separate issue, the total result of the roll often doesn't show up in the box in chat)

Foundry v9.269
Everywhen v0.9.5
No Active Modules

**Comment by waryjack** [comment]
I will look into this as soon as I can.

**Comment by Jerrikus2k** [comment]
Yep just wanted to report the same here. After last session (Nov 21) I noticed that Careers were empty. Sames version as above, all modules deactivated.

**Comment by KarstenW76** [comment]
Confirmed, same issue here. Would be great if you get the chance to fix this. Thank you in advance!

**Comment by waryjack** [comment]
Updates: I think I've got this one locked down - I'm not really a programmer (though I play one on foundry), but it appeared to be an error in the order of things I had happening, which meant that it would work once, but any dice rolls after that would be trying to work with data that no longer existed. 

I don't know why it ever worked, but my guess is changes in Foundry v9 tightened things up and made it less forgiving of my amateur mistakes.

I'll be working on the reversion of the weapon setting next, but a new release should be out soon.
