### ISSUE TITLE
Career value not being used in a roll

### ISSUE THREAD

**Issue by sm-thirdman** [waryjack/ewhen08x#2]
Hi,

i noticed that the relevant Career value was not being pulled through and added to the roll after selecting the career.  It was always zero.  I.e. by using the Basic Roll dialog box (see screenshot).

I did some digging.

In EWRoll.js, in the compileRollInfo() functiom in the Career bit of the code.  Here is a copy with some added console logging:

        if (careerName != "none") {

           let ownedItems = this.actor.items;

           let careers = this.actor.data.items.filter(function(item) {return item.type == "career"});
           let thisCareer = careers.filter(function(item) { return item.name == careerName});
           console.warn(thisCareer);
           let itemId = thisCareer[0]._id;
           console.warn("ItemId: " + itemId);
           cVal = this.actor.getOwnedItem(itemId).data.data.rank;

1.           console.warn(this.actor.items.get(itemId).data.data);
2.           console.warn(this.actor.items.get(itemId).data.data.data);

           console.warn("cVal: " + cVal);
       }

I noticed it found the Career name okay, 'Labourer' in my case.  However it wasn't pulling through the value, 3 in my case.

Looking at item data at the level of 'Item'.data.data I noticed this output from the console output at 1, above:

description: "", rank: 0, source: "", era: "", data: {…}}
data: {rank: "3"}
description: ""
era: ""
rank: 0
source: ""
__proto__: Object

It has a Rank of zero (the default), but also an additional sub data item of Rank, which is set to 3.

The second console output at 2, above, gives:

{rank: "3"}
rank: "3"
__proto__: Object

I really don't know why this is, but changing the cVal assignment to an extra level of 'data' solves the issue, e.g.:

           cVal = this.actor.items.get(itemId).data.data.data.rank;

You may be wondering why I have written all this here, rather than making a change in the code or whatever the process is.  That is simple, I have no idea how git works or what I would do, so I wrote this instead.  I also started learning javascript about 3 days ago, so I didn't want to touch the actual code.

Sam.

Screenshot:

![Screenshot 2021-06-24 at 16 59 59](https://user-images.githubusercontent.com/82657085/123297208-43950f00-d50f-11eb-88f0-719a7f9fe7dd.png)

**Comment by waryjack** [comment]
Hey, thanks! No worries about the email, and thanks for tracking that down.
I've been running into issues with this from time to time because I had to
port this system from Foundry 0.7.x to 0.8.x and that changed a bunch of
things that are still cropping up.

I appreciate it! I'll patch this, check for other similar issues, and put
out an update as soon as I can.

**Comment by waryjack** [comment]
fixed in latest update
