### ISSUE TITLE
Wrong order on Foundry package web site

### ISSUE THREAD

**Issue by farling42** [waryjack/ewhen08x#21]
Your game system is appearing in the module list on the foundery web site as being only version 9, see 

https://foundryvtt.com/packages/systems

If you remove the "v" letter from the start of each version number on the foundry package management page, then sorting will be done numerically and it will appear on the above linked page as being supported in V10.

(I note that you don't include the "v" in the actual system.json, which is a good thing :-)   )

**Comment by waryjack** [comment]
Thanks! Fixed.
