### ISSUE TITLE
Career & some attribute values not syncing between protoype token and token

### ISSUE THREAD

**Issue by sm-thirdman** [waryjack/ewhen08x#3]
If I drag a PC actor on to the scene, then double click to open the character sheet.

I then single click the same PC actor under under the Actors tab.

i now have the same character sheet open, one is a scene 'token', one is an off scene 'prototype token'. 

On the prototype token if I update Strength, Mind, Appeal, Melee, Ranged or Initiative it is upadted on the token character on field lost focus.

Agility, Defense and the four career values do not update the token version of the character.

Sam.

**Comment by waryjack** [comment]
I think this is just the way Foundry handles things: foundry has Actors,
and Tokens, and they are not *necessarily *linked together. If you drag an
actor onto the scene from the sidebar, it won't (by default) be linked to
the Actor itself - it's a new, independent "copy" of the actor.

If you set up the Prototype Token of an actor to "Link Actor Data", then
changes to the token's sheet (if you double click to open and edit it) will
save to the Actor.

The reason for this is so you can make one Actor version of a bad guy, and
drag multiple copies to the scene, and they don't interfere with each other.

However, if you're working with linked actor data and it's still not
updating, that's an issue.

**Comment by sm-thirdman** [comment]
Yep, okay.  I have just checked this and performed the linked actor, which updates both protoype and instance views of the character sheet.  This isn't an issue.

Sam
