### ISSUE TITLE
Modifier not displayed in chat output

### ISSUE THREAD

**Issue by waryjack** [waryjack/ewhen08x#8]
Fixed/flat modifiers that are part of weapon setup are not displayed in chat output; it **is** however being added in. The values are right, the display output is wrong.

**Comment by johannes-z** [comment]
I'll take a look at this!

**Comment by johannes-z** [comment]
@waryjack Can you tell me what you mean exactly? Using the master branch This is What I get in chat: 
![image](https://user-images.githubusercontent.com/9069888/125316687-a3c1e880-e338-11eb-8a9f-954f5a6cf192.png)
